version: '2'
networks:
  build-box-in-a-box:
    driver: bridge
volumes:
  sonarqube_postgres:
  sonarqube_postgres_data:
services:
  sonarqube-postgres:
    image: postgres
    networks:
      - build-box-in-a-box
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
    volumes:
      - sonarqube_postgres:/var/lib/postgres
      - sonarqube_postgres_data:/var/lib/postgresql/data
  # sonarqube-mysql:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=sonarqube
  #     - MYSQL_DATABASE=sonarqube
  #     - MYSQL_USER=sonarqube
  #     - MYSQL_PASSWORD=sonarqube
  #   volumes:
  #     - ./sonarqube_mysql_data:/var/lib/mysql
  sonarqube:
    image: sonarqube
    networks:
      - build-box-in-a-box
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-postgres:5432/sonarqube
      # - SONARQUBE_JDBC_URL=jdbc:mysql://sonarqube-mysql:3306/sonarqube
    volumes:
      - ./sonarqube_data/sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data/sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_data/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_data/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - sonarqube-postgres
  jenkins:
    image: jenkins
    networks:
      - build-box-in-a-box
    ports:
      - "8080:8080"
      - "50000:5000"
    volumes:
      - ./jenkins_data/:/var/jenkins_home
